baseURL = "https://bdashrad.com/"
languageCode = "en-us"
title = "Brad Clark"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-49441297-1"
enableRobotsTXT = true

[params]
  env = "production"
  # description = ""
  facebook = "https://facebook.com/bdashrad"
  twitter = "https://twitter.com/bdashrad"
  instagram = "https://twitter.com/bdashrad"
  github = "https://github.com/bdashrad"
  linkedin = "https://www.linkedin.com/in/bradfordclark/"
  background_color_class = "bg-black"
  featured_image = "/images/background.jpg"

[[menu.main]]
  name = "Resumé"
  idenitfier = "resume"
  url = "https://hireme.bdashrad.com/"