baseURL = "https://bdashrad.com/"
languageCode = "en-us"
title = "Home"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-49441297-1"
enableRobotsTXT = true

[params]
  description = ""
  facebook = "https://facebook.com/bdashrad"
  twitter = "https://twitter.com/bdashrad"
  instagram = "https://twitter.com/bdashrad"
  youtube = ""
  github = "https://github.com/bdashrad"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/background.jpg"

[[menu.main]]
  name = "Resumé"
  idenitfier = "resume"
  url = "https://hireme.bdashrad.com/"